language: go
sudo: false
go: 1.11.x

env: GO111MODULE=on

services:
  - docker

# for some reason /usr/local is owned by a different user in travis, so we transfer ownership to the current user:
before_install: sudo chown -R $(whoami) /usr/local

install: make all

jobs:
  include:
  - stage: docker-push
    name: "Push to dockerHub"
    script:
      - make dockerpush
