// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRequest struct {
	NodeAddress          string   `protobuf:"bytes,1,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type SubmitRequest struct {
	Challenge            []byte   `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type SubmitResponse struct {
	RoundId              string   `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitResponse) Reset()         { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()    {}
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResponse.Unmarshal(m, b)
}
func (m *SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResponse.Marshal(b, m, deterministic)
}
func (m *SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResponse.Merge(m, src)
}
func (m *SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitResponse.Size(m)
}
func (m *SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResponse proto.InternalMessageInfo

func (m *SubmitResponse) GetRoundId() string {
	if m != nil {
		return m.RoundId
	}
	return ""
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	OpenRoundId          string   `protobuf:"bytes,1,opt,name=openRoundId,proto3" json:"openRoundId,omitempty"`
	ExecutingRoundsIds   []string `protobuf:"bytes,2,rep,name=executingRoundsIds,proto3" json:"executingRoundsIds,omitempty"`
	ServicePubKey        []byte   `protobuf:"bytes,3,opt,name=servicePubKey,proto3" json:"servicePubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetOpenRoundId() string {
	if m != nil {
		return m.OpenRoundId
	}
	return ""
}

func (m *GetInfoResponse) GetExecutingRoundsIds() []string {
	if m != nil {
		return m.ExecutingRoundsIds
	}
	return nil
}

func (m *GetInfoResponse) GetServicePubKey() []byte {
	if m != nil {
		return m.ServicePubKey
	}
	return nil
}

type MembershipProof struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Proof                [][]byte `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MembershipProof) Reset()         { *m = MembershipProof{} }
func (m *MembershipProof) String() string { return proto.CompactTextString(m) }
func (*MembershipProof) ProtoMessage()    {}
func (*MembershipProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *MembershipProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipProof.Unmarshal(m, b)
}
func (m *MembershipProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipProof.Marshal(b, m, deterministic)
}
func (m *MembershipProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipProof.Merge(m, src)
}
func (m *MembershipProof) XXX_Size() int {
	return xxx_messageInfo_MembershipProof.Size(m)
}
func (m *MembershipProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipProof.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipProof proto.InternalMessageInfo

func (m *MembershipProof) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MembershipProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MembershipProof) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type PoetProof struct {
	Phi                  []byte   `protobuf:"bytes,1,opt,name=phi,proto3" json:"phi,omitempty"`
	ProvenLeaves         [][]byte `protobuf:"bytes,2,rep,name=provenLeaves,proto3" json:"provenLeaves,omitempty"`
	ProofNodes           [][]byte `protobuf:"bytes,3,rep,name=proofNodes,proto3" json:"proofNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoetProof) Reset()         { *m = PoetProof{} }
func (m *PoetProof) String() string { return proto.CompactTextString(m) }
func (*PoetProof) ProtoMessage()    {}
func (*PoetProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *PoetProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoetProof.Unmarshal(m, b)
}
func (m *PoetProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoetProof.Marshal(b, m, deterministic)
}
func (m *PoetProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoetProof.Merge(m, src)
}
func (m *PoetProof) XXX_Size() int {
	return xxx_messageInfo_PoetProof.Size(m)
}
func (m *PoetProof) XXX_DiscardUnknown() {
	xxx_messageInfo_PoetProof.DiscardUnknown(m)
}

var xxx_messageInfo_PoetProof proto.InternalMessageInfo

func (m *PoetProof) GetPhi() []byte {
	if m != nil {
		return m.Phi
	}
	return nil
}

func (m *PoetProof) GetProvenLeaves() [][]byte {
	if m != nil {
		return m.ProvenLeaves
	}
	return nil
}

func (m *PoetProof) GetProofNodes() [][]byte {
	if m != nil {
		return m.ProofNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "api.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "api.StartResponse")
	proto.RegisterType((*SubmitRequest)(nil), "api.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "api.SubmitResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*MembershipProof)(nil), "api.MembershipProof")
	proto.RegisterType((*PoetProof)(nil), "api.PoetProof")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0xe5, 0xb8, 0x69, 0xf1, 0xd4, 0xf9, 0x61, 0x08, 0x92, 0x15, 0x55, 0xc8, 0x5a, 0x71,
	0x88, 0x2a, 0x91, 0xf0, 0x73, 0xe3, 0x86, 0x84, 0x80, 0x88, 0x1f, 0x05, 0xf7, 0x09, 0x9c, 0x78,
	0x92, 0xac, 0x94, 0xee, 0x2c, 0xde, 0x75, 0x54, 0xae, 0xdc, 0x38, 0xf3, 0x68, 0xdc, 0x39, 0xf1,
	0x20, 0xc8, 0xeb, 0x6d, 0xb1, 0xa5, 0xde, 0x76, 0xbe, 0x99, 0xf9, 0xd6, 0xeb, 0x19, 0x88, 0x72,
	0x2d, 0xe7, 0xba, 0x64, 0xcb, 0x18, 0xe6, 0x5a, 0x4e, 0x2f, 0x76, 0xcc, 0xbb, 0x03, 0x2d, 0x72,
	0x2d, 0x17, 0xb9, 0x52, 0x6c, 0x73, 0x2b, 0x59, 0x99, 0xa6, 0x44, 0x3c, 0x87, 0xf8, 0xca, 0xe6,
	0xa5, 0xcd, 0xe8, 0x5b, 0x45, 0xc6, 0x62, 0x0a, 0xe7, 0x8a, 0x0b, 0x7a, 0x53, 0x14, 0x25, 0x19,
	0x93, 0x04, 0x69, 0x30, 0x8b, 0xb2, 0x36, 0x12, 0x23, 0x18, 0xf8, 0x0e, 0xa3, 0x59, 0x19, 0x12,
	0xcf, 0x60, 0x70, 0x55, 0xad, 0xaf, 0xe5, 0x9d, 0xe3, 0x02, 0xa2, 0xcd, 0x3e, 0x3f, 0x1c, 0x48,
	0xed, 0xc8, 0x19, 0xe2, 0xec, 0x3f, 0x10, 0x97, 0x30, 0xbc, 0x2d, 0x6f, 0x04, 0x98, 0xc0, 0x59,
	0xc9, 0x95, 0x2a, 0x96, 0x85, 0xbf, 0xef, 0x36, 0x14, 0x63, 0x18, 0xbe, 0x27, 0xbb, 0x54, 0x5b,
	0xf6, 0x6e, 0xf1, 0x33, 0x80, 0xd1, 0x1d, 0xf2, 0xfd, 0x29, 0x9c, 0xb3, 0x26, 0x95, 0x75, 0x1c,
	0x6d, 0x84, 0x73, 0x40, 0xba, 0xa1, 0x4d, 0x65, 0xa5, 0xda, 0x39, 0x66, 0x96, 0x85, 0x49, 0x7a,
	0x69, 0x38, 0x8b, 0xb2, 0x7b, 0x32, 0xf8, 0x14, 0x06, 0x86, 0xca, 0xa3, 0xdc, 0xd0, 0xaa, 0x5a,
	0x7f, 0xa4, 0xef, 0x49, 0xe8, 0x5e, 0xd1, 0x85, 0xe2, 0x2b, 0x8c, 0x3e, 0xd3, 0xf5, 0x9a, 0x4a,
	0xb3, 0x97, 0x7a, 0x55, 0x32, 0x6f, 0x71, 0x02, 0x7d, 0xa9, 0x0a, 0xba, 0x71, 0x1f, 0xd1, 0xcf,
	0x9a, 0x00, 0x11, 0x4e, 0x4a, 0x66, 0x9b, 0xf4, 0x9c, 0xc5, 0x9d, 0xeb, 0x4a, 0x5d, 0xb7, 0x24,
	0x61, 0x1a, 0xce, 0xe2, 0xac, 0x09, 0x44, 0x0e, 0xd1, 0x8a, 0xc9, 0x36, 0xb2, 0x31, 0x84, 0x7a,
	0x2f, 0xfd, 0x1f, 0xac, 0x8f, 0x28, 0x20, 0xd6, 0x25, 0x1f, 0x49, 0x7d, 0xa2, 0xfc, 0x48, 0xcd,
	0x0b, 0xe2, 0xac, 0xc3, 0xf0, 0x09, 0x80, 0x73, 0x7d, 0xe1, 0x82, 0x8c, 0xb7, 0xb7, 0xc8, 0xcb,
	0x3f, 0x01, 0x9c, 0xd4, 0x77, 0xe0, 0x5b, 0xe8, 0xbb, 0x41, 0xe2, 0xc3, 0x79, 0xbd, 0x32, 0xed,
	0x35, 0x98, 0x62, 0x1b, 0xf9, 0x39, 0x4f, 0x7e, 0xfc, 0xfe, 0xfb, 0xab, 0x37, 0x14, 0xd1, 0xe2,
	0xf8, 0x62, 0x61, 0xea, 0xd4, 0xeb, 0xe0, 0x12, 0x3f, 0xc0, 0x69, 0x33, 0x4e, 0xf4, 0x3d, 0xed,
	0x55, 0x98, 0x3e, 0xea, 0x30, 0x2f, 0x7a, 0xec, 0x44, 0x23, 0x01, 0x4e, 0xe4, 0x72, 0xb5, 0xe9,
	0x1d, 0x9c, 0xf9, 0xc9, 0x62, 0xd3, 0xd6, 0x1d, 0xfd, 0x74, 0xd2, 0x85, 0x5e, 0x36, 0x76, 0x32,
	0xc0, 0x07, 0xb5, 0x4c, 0xaa, 0x2d, 0xaf, 0x4f, 0xdd, 0x66, 0xbf, 0xfa, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x5c, 0x5c, 0x74, 0xba, 0x09, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoetClient is the client API for Poet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoetClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type poetClient struct {
	cc *grpc.ClientConn
}

func NewPoetClient(cc *grpc.ClientConn) PoetClient {
	return &poetClient{cc}
}

func (c *poetClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoetServer is the server API for Poet service.
type PoetServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
}

func RegisterPoetServer(s *grpc.Server, srv PoetServer) {
	s.RegisterService(&_Poet_serviceDesc, srv)
}

func _Poet_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Poet",
	HandlerType: (*PoetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Poet_Start_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Poet_Submit_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Poet_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
