// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
	GatewayAddresses       []string `protobuf:"bytes,1,rep,name=gatewayAddresses,proto3" json:"gatewayAddresses,omitempty"`
	DisableBroadcast       bool     `protobuf:"varint,2,opt,name=disableBroadcast,proto3" json:"disableBroadcast,omitempty"`
	ConnAcksThreshold      int32    `protobuf:"varint,3,opt,name=connAcksThreshold,proto3" json:"connAcksThreshold,omitempty"`
	BroadcastAcksThreshold int32    `protobuf:"varint,4,opt,name=broadcastAcksThreshold,proto3" json:"broadcastAcksThreshold,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetGatewayAddresses() []string {
	if m != nil {
		return m.GatewayAddresses
	}
	return nil
}

func (m *StartRequest) GetDisableBroadcast() bool {
	if m != nil {
		return m.DisableBroadcast
	}
	return false
}

func (m *StartRequest) GetConnAcksThreshold() int32 {
	if m != nil {
		return m.ConnAcksThreshold
	}
	return 0
}

func (m *StartRequest) GetBroadcastAcksThreshold() int32 {
	if m != nil {
		return m.BroadcastAcksThreshold
	}
	return 0
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

type UpdateGatewayRequest struct {
	GatewayAddresses       []string `protobuf:"bytes,1,rep,name=gatewayAddresses,proto3" json:"gatewayAddresses,omitempty"`
	DisableBroadcast       bool     `protobuf:"varint,2,opt,name=disableBroadcast,proto3" json:"disableBroadcast,omitempty"`
	ConnAcksThreshold      int32    `protobuf:"varint,3,opt,name=connAcksThreshold,proto3" json:"connAcksThreshold,omitempty"`
	BroadcastAcksThreshold int32    `protobuf:"varint,4,opt,name=broadcastAcksThreshold,proto3" json:"broadcastAcksThreshold,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *UpdateGatewayRequest) Reset()         { *m = UpdateGatewayRequest{} }
func (m *UpdateGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGatewayRequest) ProtoMessage()    {}
func (*UpdateGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *UpdateGatewayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGatewayRequest.Unmarshal(m, b)
}
func (m *UpdateGatewayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGatewayRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGatewayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGatewayRequest.Merge(m, src)
}
func (m *UpdateGatewayRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGatewayRequest.Size(m)
}
func (m *UpdateGatewayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGatewayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGatewayRequest proto.InternalMessageInfo

func (m *UpdateGatewayRequest) GetGatewayAddresses() []string {
	if m != nil {
		return m.GatewayAddresses
	}
	return nil
}

func (m *UpdateGatewayRequest) GetDisableBroadcast() bool {
	if m != nil {
		return m.DisableBroadcast
	}
	return false
}

func (m *UpdateGatewayRequest) GetConnAcksThreshold() int32 {
	if m != nil {
		return m.ConnAcksThreshold
	}
	return 0
}

func (m *UpdateGatewayRequest) GetBroadcastAcksThreshold() int32 {
	if m != nil {
		return m.BroadcastAcksThreshold
	}
	return 0
}

type UpdateGatewayResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGatewayResponse) Reset()         { *m = UpdateGatewayResponse{} }
func (m *UpdateGatewayResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGatewayResponse) ProtoMessage()    {}
func (*UpdateGatewayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *UpdateGatewayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGatewayResponse.Unmarshal(m, b)
}
func (m *UpdateGatewayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGatewayResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGatewayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGatewayResponse.Merge(m, src)
}
func (m *UpdateGatewayResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGatewayResponse.Size(m)
}
func (m *UpdateGatewayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGatewayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGatewayResponse proto.InternalMessageInfo

type SubmitRequest struct {
	Challenge            []byte   `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type SubmitResponse struct {
	RoundId              string   `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitResponse) Reset()         { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()    {}
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResponse.Unmarshal(m, b)
}
func (m *SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResponse.Marshal(b, m, deterministic)
}
func (m *SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResponse.Merge(m, src)
}
func (m *SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitResponse.Size(m)
}
func (m *SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResponse proto.InternalMessageInfo

func (m *SubmitResponse) GetRoundId() string {
	if m != nil {
		return m.RoundId
	}
	return ""
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	OpenRoundId          string   `protobuf:"bytes,1,opt,name=openRoundId,proto3" json:"openRoundId,omitempty"`
	ExecutingRoundsIds   []string `protobuf:"bytes,2,rep,name=executingRoundsIds,proto3" json:"executingRoundsIds,omitempty"`
	ServicePubKey        []byte   `protobuf:"bytes,3,opt,name=servicePubKey,proto3" json:"servicePubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetOpenRoundId() string {
	if m != nil {
		return m.OpenRoundId
	}
	return ""
}

func (m *GetInfoResponse) GetExecutingRoundsIds() []string {
	if m != nil {
		return m.ExecutingRoundsIds
	}
	return nil
}

func (m *GetInfoResponse) GetServicePubKey() []byte {
	if m != nil {
		return m.ServicePubKey
	}
	return nil
}

type MembershipProof struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Proof                [][]byte `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MembershipProof) Reset()         { *m = MembershipProof{} }
func (m *MembershipProof) String() string { return proto.CompactTextString(m) }
func (*MembershipProof) ProtoMessage()    {}
func (*MembershipProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *MembershipProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipProof.Unmarshal(m, b)
}
func (m *MembershipProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipProof.Marshal(b, m, deterministic)
}
func (m *MembershipProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipProof.Merge(m, src)
}
func (m *MembershipProof) XXX_Size() int {
	return xxx_messageInfo_MembershipProof.Size(m)
}
func (m *MembershipProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipProof.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipProof proto.InternalMessageInfo

func (m *MembershipProof) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MembershipProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MembershipProof) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type PoetProof struct {
	Phi                  []byte   `protobuf:"bytes,1,opt,name=phi,proto3" json:"phi,omitempty"`
	ProvenLeaves         [][]byte `protobuf:"bytes,2,rep,name=provenLeaves,proto3" json:"provenLeaves,omitempty"`
	ProofNodes           [][]byte `protobuf:"bytes,3,rep,name=proofNodes,proto3" json:"proofNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoetProof) Reset()         { *m = PoetProof{} }
func (m *PoetProof) String() string { return proto.CompactTextString(m) }
func (*PoetProof) ProtoMessage()    {}
func (*PoetProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *PoetProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoetProof.Unmarshal(m, b)
}
func (m *PoetProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoetProof.Marshal(b, m, deterministic)
}
func (m *PoetProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoetProof.Merge(m, src)
}
func (m *PoetProof) XXX_Size() int {
	return xxx_messageInfo_PoetProof.Size(m)
}
func (m *PoetProof) XXX_DiscardUnknown() {
	xxx_messageInfo_PoetProof.DiscardUnknown(m)
}

var xxx_messageInfo_PoetProof proto.InternalMessageInfo

func (m *PoetProof) GetPhi() []byte {
	if m != nil {
		return m.Phi
	}
	return nil
}

func (m *PoetProof) GetProvenLeaves() [][]byte {
	if m != nil {
		return m.ProvenLeaves
	}
	return nil
}

func (m *PoetProof) GetProofNodes() [][]byte {
	if m != nil {
		return m.ProofNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "api.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "api.StartResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "api.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "api.ShutdownResponse")
	proto.RegisterType((*UpdateGatewayRequest)(nil), "api.UpdateGatewayRequest")
	proto.RegisterType((*UpdateGatewayResponse)(nil), "api.UpdateGatewayResponse")
	proto.RegisterType((*SubmitRequest)(nil), "api.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "api.SubmitResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*MembershipProof)(nil), "api.MembershipProof")
	proto.RegisterType((*PoetProof)(nil), "api.PoetProof")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xb5, 0xdd, 0xa4, 0x6d, 0x86, 0x4d, 0x93, 0xb8, 0x69, 0x59, 0x56, 0x15, 0x8a, 0x2c,
	0x0e, 0x51, 0x05, 0x8d, 0x00, 0x89, 0x03, 0xb7, 0x22, 0x44, 0xa9, 0xf8, 0xa3, 0xb2, 0x81, 0x07,
	0x70, 0xe2, 0x69, 0xb2, 0x22, 0xb5, 0xcd, 0xda, 0x9b, 0xb6, 0x57, 0x6e, 0x5c, 0xb8, 0xf0, 0x5a,
	0xdc, 0xe0, 0x11, 0x78, 0x10, 0xb4, 0xb6, 0xd3, 0x66, 0xdb, 0xf0, 0x02, 0xdc, 0xd6, 0xdf, 0xcc,
	0xfc, 0xe2, 0x6f, 0x3c, 0x13, 0x68, 0x30, 0x95, 0x1d, 0xa8, 0x5c, 0x1a, 0x49, 0x42, 0xa6, 0xb2,
	0x64, 0x6f, 0x22, 0xe5, 0x64, 0x86, 0x03, 0xa6, 0xb2, 0x01, 0x13, 0x42, 0x1a, 0x66, 0x32, 0x29,
	0xb4, 0x4b, 0xa1, 0x3f, 0x03, 0x88, 0x86, 0x86, 0xe5, 0x26, 0xc5, 0x2f, 0x05, 0x6a, 0x43, 0xf6,
	0xa1, 0x3d, 0x61, 0x06, 0xcf, 0xd9, 0xe5, 0x21, 0xe7, 0x39, 0x6a, 0x8d, 0x3a, 0x0e, 0x7a, 0x61,
	0xbf, 0x91, 0xde, 0xd2, 0xcb, 0x5c, 0x9e, 0x69, 0x36, 0x9a, 0xe1, 0x8b, 0x5c, 0x32, 0x3e, 0x66,
	0xda, 0xc4, 0x6b, 0xbd, 0xa0, 0xbf, 0x99, 0xde, 0xd2, 0xc9, 0x43, 0xe8, 0x8c, 0xa5, 0x10, 0x87,
	0xe3, 0xcf, 0xfa, 0xe3, 0x34, 0x47, 0x3d, 0x95, 0x33, 0x1e, 0x87, 0xbd, 0xa0, 0x5f, 0x4f, 0x6f,
	0x07, 0xc8, 0x33, 0xd8, 0x1d, 0x2d, 0x4a, 0xab, 0x25, 0x35, 0x5b, 0xf2, 0x8f, 0x28, 0x6d, 0x41,
	0xd3, 0xbb, 0xd1, 0x4a, 0x0a, 0x8d, 0xb4, 0x03, 0xad, 0xe1, 0xb4, 0x30, 0x5c, 0x9e, 0x0b, 0xef,
	0x90, 0x12, 0x68, 0x5f, 0x4b, 0x3e, 0xed, 0x77, 0x00, 0xdd, 0x4f, 0x8a, 0x33, 0x83, 0x47, 0xce,
	0xe4, 0xff, 0xd1, 0x8e, 0xbb, 0xb0, 0x73, 0xc3, 0x95, 0xf7, 0xfb, 0x08, 0x9a, 0xc3, 0x62, 0x74,
	0x96, 0x5d, 0x3d, 0xfb, 0x1e, 0x34, 0xc6, 0x53, 0x36, 0x9b, 0xa1, 0x98, 0x60, 0x1c, 0xf4, 0x82,
	0x7e, 0x94, 0x5e, 0x0b, 0x74, 0x1f, 0xb6, 0x16, 0xe9, 0x0e, 0x40, 0x62, 0xd8, 0xc8, 0x65, 0x21,
	0xf8, 0x31, 0xb7, 0xd9, 0x8d, 0x74, 0x71, 0xa4, 0x6d, 0xd8, 0x3a, 0x42, 0x73, 0x2c, 0x4e, 0xe5,
	0xa2, 0xe1, 0xdf, 0x02, 0x68, 0x5d, 0x49, 0xbe, 0xbe, 0x07, 0x77, 0xa4, 0x42, 0x91, 0x56, 0x18,
	0xcb, 0x12, 0x39, 0x00, 0x82, 0x17, 0x38, 0x2e, 0x4c, 0x26, 0x26, 0x56, 0xd3, 0xc7, 0x5c, 0xc7,
	0x6b, 0xb6, 0xf7, 0x2b, 0x22, 0xe4, 0x01, 0x34, 0x35, 0xe6, 0xf3, 0x6c, 0x8c, 0x27, 0xc5, 0xe8,
	0x0d, 0x5e, 0xda, 0x6e, 0x46, 0x69, 0x55, 0xa4, 0x1f, 0xa0, 0xf5, 0x0e, 0xcf, 0x46, 0x98, 0xeb,
	0x69, 0xa6, 0x4e, 0x72, 0x29, 0x4f, 0x49, 0x17, 0xea, 0x99, 0xe0, 0x78, 0x61, 0x2f, 0x51, 0x4f,
	0xdd, 0x81, 0x10, 0xa8, 0xe5, 0x52, 0xba, 0x07, 0x8c, 0x52, 0xfb, 0x5d, 0x66, 0xaa, 0xb2, 0x24,
	0x0e, 0x7b, 0x61, 0x3f, 0x4a, 0xdd, 0x81, 0x32, 0x68, 0x9c, 0x48, 0x34, 0x0e, 0xd6, 0x86, 0x50,
	0x4d, 0x33, 0xdf, 0xc1, 0xf2, 0x93, 0x50, 0x88, 0x54, 0x2e, 0xe7, 0x28, 0xde, 0x22, 0x9b, 0xa3,
	0x73, 0x10, 0xa5, 0x15, 0x8d, 0xdc, 0x07, 0xb0, 0xac, 0xf7, 0x92, 0xa3, 0xf6, 0xf4, 0x25, 0xe5,
	0xc9, 0xf7, 0x10, 0x6a, 0xe5, 0x6f, 0x90, 0x97, 0x50, 0xb7, 0xf3, 0x4d, 0x3a, 0x07, 0xe5, 0x9a,
	0x2f, 0x6f, 0x6e, 0x42, 0x96, 0x25, 0xff, 0xce, 0xdd, 0xaf, 0xbf, 0xfe, 0xfc, 0x58, 0xdb, 0xa2,
	0x8d, 0xc1, 0xfc, 0xf1, 0x40, 0x97, 0xa1, 0xe7, 0xc1, 0x3e, 0x79, 0x0d, 0xb5, 0xa1, 0x91, 0x8a,
	0x74, 0x5d, 0x45, 0x75, 0x3f, 0x92, 0x9d, 0x1b, 0xaa, 0x47, 0x6d, 0x5b, 0x54, 0x93, 0x6e, 0x3a,
	0x94, 0x54, 0x25, 0x89, 0x43, 0xb3, 0x32, 0x60, 0xe4, 0x9e, 0x2d, 0x5e, 0xb5, 0x4a, 0x49, 0xb2,
	0x2a, 0xe4, 0xe1, 0x7b, 0x16, 0xbe, 0x4b, 0x3b, 0x25, 0xbc, 0xb0, 0x29, 0x7e, 0xbd, 0xdc, 0x7d,
	0xd7, 0xdd, 0xf8, 0x11, 0xef, 0x71, 0x79, 0x74, 0x93, 0xed, 0x8a, 0xe6, 0x81, 0x3b, 0x16, 0xd8,
	0xa2, 0x60, 0x6f, 0x6b, 0x63, 0x25, 0xe9, 0x15, 0x6c, 0xf8, 0x49, 0x24, 0xae, 0xac, 0x3a, 0xaa,
	0x49, 0xb7, 0x2a, 0x7a, 0x58, 0xdb, 0xc2, 0x80, 0x58, 0xeb, 0x99, 0x38, 0x95, 0xa3, 0x75, 0xfb,
	0xef, 0xf9, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x2e, 0xcc, 0x8e, 0x6d, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoetClient is the client API for Poet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoetClient interface {
	//*
	//Start is used to start the service.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	//*
	//Stop is used to stop the service.
	Stop(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	//*
	//UpdateGateway allows to update the list of gateway addresses (with additional broadcasting config),
	//similar to the Start rpc, but after the service already started.
	UpdateGateway(ctx context.Context, in *UpdateGatewayRequest, opts ...grpc.CallOption) (*UpdateGatewayResponse, error)
	//*
	//Submit adds a challenge to the service's current open round,
	//to be included its later generated proof.
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	//*
	//GetInfo returns general information concerning the service,
	//including its identity pubkey.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type poetClient struct {
	cc *grpc.ClientConn
}

func NewPoetClient(cc *grpc.ClientConn) PoetClient {
	return &poetClient{cc}
}

func (c *poetClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) Stop(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) UpdateGateway(ctx context.Context, in *UpdateGatewayRequest, opts ...grpc.CallOption) (*UpdateGatewayResponse, error) {
	out := new(UpdateGatewayResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/UpdateGateway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoetServer is the server API for Poet service.
type PoetServer interface {
	//*
	//Start is used to start the service.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	//*
	//Stop is used to stop the service.
	Stop(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	//*
	//UpdateGateway allows to update the list of gateway addresses (with additional broadcasting config),
	//similar to the Start rpc, but after the service already started.
	UpdateGateway(context.Context, *UpdateGatewayRequest) (*UpdateGatewayResponse, error)
	//*
	//Submit adds a challenge to the service's current open round,
	//to be included its later generated proof.
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	//*
	//GetInfo returns general information concerning the service,
	//including its identity pubkey.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
}

func RegisterPoetServer(s *grpc.Server, srv PoetServer) {
	s.RegisterService(&_Poet_serviceDesc, srv)
}

func _Poet_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).Stop(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_UpdateGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).UpdateGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/UpdateGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).UpdateGateway(ctx, req.(*UpdateGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Poet",
	HandlerType: (*PoetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Poet_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Poet_Stop_Handler,
		},
		{
			MethodName: "UpdateGateway",
			Handler:    _Poet_UpdateGateway_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Poet_Submit_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Poet_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
