// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitCommitmentRequest struct {
	Commitment           []byte   `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCommitmentRequest) Reset()         { *m = SubmitCommitmentRequest{} }
func (m *SubmitCommitmentRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitCommitmentRequest) ProtoMessage()    {}
func (*SubmitCommitmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SubmitCommitmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCommitmentRequest.Unmarshal(m, b)
}
func (m *SubmitCommitmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCommitmentRequest.Marshal(b, m, deterministic)
}
func (m *SubmitCommitmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCommitmentRequest.Merge(m, src)
}
func (m *SubmitCommitmentRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitCommitmentRequest.Size(m)
}
func (m *SubmitCommitmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCommitmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCommitmentRequest proto.InternalMessageInfo

func (m *SubmitCommitmentRequest) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

type SubmitCommitmentResponse struct {
	RoundId              int32    `protobuf:"varint,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCommitmentResponse) Reset()         { *m = SubmitCommitmentResponse{} }
func (m *SubmitCommitmentResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitCommitmentResponse) ProtoMessage()    {}
func (*SubmitCommitmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SubmitCommitmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCommitmentResponse.Unmarshal(m, b)
}
func (m *SubmitCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCommitmentResponse.Marshal(b, m, deterministic)
}
func (m *SubmitCommitmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCommitmentResponse.Merge(m, src)
}
func (m *SubmitCommitmentResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitCommitmentResponse.Size(m)
}
func (m *SubmitCommitmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCommitmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCommitmentResponse proto.InternalMessageInfo

func (m *SubmitCommitmentResponse) GetRoundId() int32 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type GetMembershipProofRequest struct {
	RoundId              int32    `protobuf:"varint,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Commitment           []byte   `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMembershipProofRequest) Reset()         { *m = GetMembershipProofRequest{} }
func (m *GetMembershipProofRequest) String() string { return proto.CompactTextString(m) }
func (*GetMembershipProofRequest) ProtoMessage()    {}
func (*GetMembershipProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GetMembershipProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMembershipProofRequest.Unmarshal(m, b)
}
func (m *GetMembershipProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMembershipProofRequest.Marshal(b, m, deterministic)
}
func (m *GetMembershipProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMembershipProofRequest.Merge(m, src)
}
func (m *GetMembershipProofRequest) XXX_Size() int {
	return xxx_messageInfo_GetMembershipProofRequest.Size(m)
}
func (m *GetMembershipProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMembershipProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMembershipProofRequest proto.InternalMessageInfo

func (m *GetMembershipProofRequest) GetRoundId() int32 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *GetMembershipProofRequest) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

type GetMembershipProofResponse struct {
	MerkleProof          [][]byte `protobuf:"bytes,1,rep,name=merkleProof,proto3" json:"merkleProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMembershipProofResponse) Reset()         { *m = GetMembershipProofResponse{} }
func (m *GetMembershipProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetMembershipProofResponse) ProtoMessage()    {}
func (*GetMembershipProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetMembershipProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMembershipProofResponse.Unmarshal(m, b)
}
func (m *GetMembershipProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMembershipProofResponse.Marshal(b, m, deterministic)
}
func (m *GetMembershipProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMembershipProofResponse.Merge(m, src)
}
func (m *GetMembershipProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetMembershipProofResponse.Size(m)
}
func (m *GetMembershipProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMembershipProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMembershipProofResponse proto.InternalMessageInfo

func (m *GetMembershipProofResponse) GetMerkleProof() [][]byte {
	if m != nil {
		return m.MerkleProof
	}
	return nil
}

type GetRoundInfoResponse struct {
	Opened               int64    `protobuf:"varint,1,opt,name=opened,proto3" json:"opened,omitempty"`
	ExecuteStart         int64    `protobuf:"varint,2,opt,name=executeStart,proto3" json:"executeStart,omitempty"`
	ExecuteEnd           int64    `protobuf:"varint,3,opt,name=executeEnd,proto3" json:"executeEnd,omitempty"`
	NumOfcommitments     int32    `protobuf:"varint,4,opt,name=numOfcommitments,proto3" json:"numOfcommitments,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,5,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	Nip                  *Proof   `protobuf:"bytes,6,opt,name=nip,proto3" json:"nip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoundInfoResponse) Reset()         { *m = GetRoundInfoResponse{} }
func (m *GetRoundInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoundInfoResponse) ProtoMessage()    {}
func (*GetRoundInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetRoundInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoundInfoResponse.Unmarshal(m, b)
}
func (m *GetRoundInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoundInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetRoundInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoundInfoResponse.Merge(m, src)
}
func (m *GetRoundInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoundInfoResponse.Size(m)
}
func (m *GetRoundInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoundInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoundInfoResponse proto.InternalMessageInfo

func (m *GetRoundInfoResponse) GetOpened() int64 {
	if m != nil {
		return m.Opened
	}
	return 0
}

func (m *GetRoundInfoResponse) GetExecuteStart() int64 {
	if m != nil {
		return m.ExecuteStart
	}
	return 0
}

func (m *GetRoundInfoResponse) GetExecuteEnd() int64 {
	if m != nil {
		return m.ExecuteEnd
	}
	return 0
}

func (m *GetRoundInfoResponse) GetNumOfcommitments() int32 {
	if m != nil {
		return m.NumOfcommitments
	}
	return 0
}

func (m *GetRoundInfoResponse) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *GetRoundInfoResponse) GetNip() *Proof {
	if m != nil {
		return m.Nip
	}
	return nil
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	OpenRoundId          int32    `protobuf:"varint,1,opt,name=openRoundId,proto3" json:"openRoundId,omitempty"`
	ExecutingRoundsIds   []int32  `protobuf:"varint,2,rep,packed,name=executingRoundsIds,proto3" json:"executingRoundsIds,omitempty"`
	ExecutedRoundsIds    []int32  `protobuf:"varint,3,rep,packed,name=executedRoundsIds,proto3" json:"executedRoundsIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetOpenRoundId() int32 {
	if m != nil {
		return m.OpenRoundId
	}
	return 0
}

func (m *GetInfoResponse) GetExecutingRoundsIds() []int32 {
	if m != nil {
		return m.ExecutingRoundsIds
	}
	return nil
}

func (m *GetInfoResponse) GetExecutedRoundsIds() []int32 {
	if m != nil {
		return m.ExecutedRoundsIds
	}
	return nil
}

type GetRoundInfoRequest struct {
	RoundId              int32    `protobuf:"varint,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoundInfoRequest) Reset()         { *m = GetRoundInfoRequest{} }
func (m *GetRoundInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoundInfoRequest) ProtoMessage()    {}
func (*GetRoundInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetRoundInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoundInfoRequest.Unmarshal(m, b)
}
func (m *GetRoundInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoundInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetRoundInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoundInfoRequest.Merge(m, src)
}
func (m *GetRoundInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoundInfoRequest.Size(m)
}
func (m *GetRoundInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoundInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoundInfoRequest proto.InternalMessageInfo

func (m *GetRoundInfoRequest) GetRoundId() int32 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type Proof struct {
	Phi                  []byte    `protobuf:"bytes,1,opt,name=phi,proto3" json:"phi,omitempty"`
	L                    []*Labels `protobuf:"bytes,2,rep,name=l,proto3" json:"l,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetPhi() []byte {
	if m != nil {
		return m.Phi
	}
	return nil
}

func (m *Proof) GetL() []*Labels {
	if m != nil {
		return m.L
	}
	return nil
}

type Labels struct {
	Labels               [][]byte `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Labels) Reset()         { *m = Labels{} }
func (m *Labels) String() string { return proto.CompactTextString(m) }
func (*Labels) ProtoMessage()    {}
func (*Labels) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *Labels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Labels.Unmarshal(m, b)
}
func (m *Labels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Labels.Marshal(b, m, deterministic)
}
func (m *Labels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Labels.Merge(m, src)
}
func (m *Labels) XXX_Size() int {
	return xxx_messageInfo_Labels.Size(m)
}
func (m *Labels) XXX_DiscardUnknown() {
	xxx_messageInfo_Labels.DiscardUnknown(m)
}

var xxx_messageInfo_Labels proto.InternalMessageInfo

func (m *Labels) GetLabels() [][]byte {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*SubmitCommitmentRequest)(nil), "api.SubmitCommitmentRequest")
	proto.RegisterType((*SubmitCommitmentResponse)(nil), "api.SubmitCommitmentResponse")
	proto.RegisterType((*GetMembershipProofRequest)(nil), "api.GetMembershipProofRequest")
	proto.RegisterType((*GetMembershipProofResponse)(nil), "api.GetMembershipProofResponse")
	proto.RegisterType((*GetRoundInfoResponse)(nil), "api.GetRoundInfoResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*GetRoundInfoRequest)(nil), "api.GetRoundInfoRequest")
	proto.RegisterType((*Proof)(nil), "api.Proof")
	proto.RegisterType((*Labels)(nil), "api.Labels")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0x26, 0x85, 0x49, 0x44, 0xc3, 0xb4, 0x50, 0x27, 0x0a, 0xad, 0x59, 0x2e, 0xa1,
	0x42, 0xb1, 0x08, 0xbd, 0xc0, 0x81, 0x0b, 0x82, 0xa8, 0x12, 0x88, 0x6a, 0x2b, 0x1e, 0xc0, 0xa9,
	0x37, 0xe9, 0x0a, 0x7b, 0xd7, 0xd8, 0x1b, 0x84, 0x54, 0x55, 0x42, 0xbc, 0x01, 0xe2, 0x01, 0x78,
	0x28, 0xae, 0x1c, 0x79, 0x10, 0xb4, 0xeb, 0x4d, 0xec, 0xfc, 0xa9, 0x37, 0xcf, 0x37, 0xb3, 0xdf,
	0xf7, 0xcd, 0xec, 0xac, 0xe1, 0x6e, 0x98, 0xf2, 0x41, 0x9a, 0x49, 0x25, 0xd1, 0x0d, 0x53, 0xde,
	0xed, 0x4d, 0xa5, 0x9c, 0xc6, 0x2c, 0x08, 0x53, 0x1e, 0x84, 0x42, 0x48, 0x15, 0x2a, 0x2e, 0x45,
	0x5e, 0x94, 0x90, 0x97, 0x70, 0x78, 0x31, 0x1b, 0x27, 0x5c, 0xbd, 0x91, 0x49, 0xc2, 0x55, 0xc2,
	0x84, 0xa2, 0xec, 0xcb, 0x8c, 0xe5, 0x0a, 0x8f, 0x00, 0x2e, 0x17, 0xa0, 0xe7, 0xf8, 0x4e, 0xbf,
	0x45, 0x2b, 0x08, 0x39, 0x05, 0x6f, 0xfd, 0x68, 0x9e, 0x4a, 0x91, 0x33, 0xf4, 0x60, 0x37, 0x93,
	0x33, 0x11, 0x9d, 0x45, 0xe6, 0x60, 0x9d, 0xce, 0x43, 0xf2, 0x09, 0x3a, 0x23, 0xa6, 0x3e, 0xb0,
	0x64, 0xcc, 0xb2, 0xfc, 0x8a, 0xa7, 0xe7, 0x99, 0x94, 0x93, 0xb9, 0xe4, 0xd6, 0x63, 0x2b, 0x66,
	0x6a, 0x6b, 0x66, 0x5e, 0x43, 0x77, 0x13, 0xad, 0xb5, 0xe3, 0x43, 0x33, 0x61, 0xd9, 0xe7, 0x98,
	0x19, 0xd8, 0x73, 0x7c, 0xb7, 0xdf, 0xa2, 0x55, 0x88, 0xfc, 0x75, 0xe0, 0x60, 0xc4, 0x14, 0x35,
	0x72, 0x62, 0x22, 0x17, 0x47, 0x1f, 0x42, 0x43, 0xa6, 0x4c, 0xb0, 0xc2, 0x91, 0x4b, 0x6d, 0x84,
	0x04, 0x5a, 0xec, 0x1b, 0xbb, 0x9c, 0x29, 0x76, 0xa1, 0xc2, 0xac, 0xb0, 0xe4, 0xd2, 0x25, 0x4c,
	0x9b, 0xb6, 0xf1, 0x5b, 0x11, 0x79, 0xae, 0xa9, 0xa8, 0x20, 0x78, 0x02, 0x6d, 0x31, 0x4b, 0x3e,
	0x4e, 0xca, 0x3e, 0x72, 0x6f, 0xc7, 0xf4, 0xbd, 0x86, 0x6b, 0xae, 0xc2, 0x2f, 0x95, 0x52, 0x79,
	0xf5, 0x62, 0x00, 0x25, 0x82, 0x3d, 0x70, 0x05, 0x4f, 0xbd, 0x86, 0xef, 0xf4, 0x9b, 0x43, 0x18,
	0xe8, 0x25, 0x28, 0x66, 0xa0, 0x61, 0xd2, 0x86, 0x7b, 0x23, 0xa6, 0x8a, 0xc6, 0xcc, 0xa8, 0xc9,
	0x4f, 0x07, 0xf6, 0x16, 0x50, 0x39, 0x26, 0xdd, 0x1d, 0x5d, 0xba, 0x82, 0x2a, 0x84, 0x03, 0xc0,
	0xc2, 0x3f, 0x17, 0x53, 0x83, 0xe5, 0x67, 0x51, 0xee, 0xd5, 0x7c, 0xb7, 0x5f, 0xa7, 0x1b, 0x32,
	0xf8, 0x0c, 0xee, 0xdb, 0x7e, 0xa3, 0xb2, 0xdc, 0x35, 0xe5, 0xeb, 0x09, 0x12, 0xc0, 0xfe, 0xf2,
	0x1d, 0xdc, 0xb2, 0x15, 0xe4, 0x14, 0xea, 0xa6, 0x49, 0x6c, 0x83, 0x9b, 0x5e, 0x71, 0xbb, 0xa4,
	0xfa, 0x13, 0x3b, 0xe0, 0xc4, 0xc6, 0x58, 0x73, 0xd8, 0x34, 0xd3, 0x78, 0x1f, 0x8e, 0x59, 0x9c,
	0x53, 0x27, 0x26, 0x3e, 0x34, 0x8a, 0x40, 0x5f, 0x6e, 0x6c, 0xbe, 0xec, 0x4a, 0xd8, 0x68, 0xf8,
	0xdb, 0x85, 0x9d, 0x73, 0xc9, 0x14, 0x4e, 0xa0, 0xbd, 0xba, 0xe3, 0xd8, 0x33, 0x74, 0x5b, 0x5e,
	0x4d, 0xf7, 0xd1, 0x96, 0x6c, 0x31, 0x62, 0xf2, 0xe0, 0xc7, 0x9f, 0x7f, 0xbf, 0x6a, 0x7b, 0x04,
	0x82, 0xaf, 0xcf, 0x83, 0xdc, 0x54, 0xbd, 0x72, 0x4e, 0xf0, 0xbb, 0x03, 0xb8, 0xbe, 0xbf, 0x78,
	0x64, 0xc8, 0xb6, 0xbe, 0x97, 0xee, 0xf1, 0xd6, 0xbc, 0x95, 0x7b, 0x6a, 0xe4, 0x9e, 0xe0, 0x63,
	0x2d, 0x97, 0xa4, 0x3a, 0x17, 0x5c, 0xdb, 0xe9, 0xdd, 0x04, 0xd7, 0xe5, 0x82, 0xdd, 0x60, 0x04,
	0xad, 0xea, 0xf0, 0xd1, 0x9b, 0x73, 0xaf, 0xde, 0x47, 0xb7, 0xb3, 0x21, 0x63, 0xf5, 0x8e, 0x8d,
	0x5e, 0x07, 0x0f, 0xb5, 0x9e, 0xd1, 0xe1, 0x62, 0x22, 0x4b, 0x49, 0x7c, 0x07, 0xbb, 0x76, 0xeb,
	0x70, 0x7f, 0x4e, 0x53, 0xe5, 0x3e, 0x58, 0x06, 0x2d, 0x6d, 0xdb, 0xd0, 0x02, 0xde, 0xd1, 0xb4,
	0x9a, 0x71, 0xdc, 0x30, 0xbf, 0xaf, 0x17, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x96, 0x7b,
	0xf2, 0xee, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoetClient is the client API for Poet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoetClient interface {
	SubmitCommitment(ctx context.Context, in *SubmitCommitmentRequest, opts ...grpc.CallOption) (*SubmitCommitmentResponse, error)
	GetMembershipProof(ctx context.Context, in *GetMembershipProofRequest, opts ...grpc.CallOption) (*GetMembershipProofResponse, error)
	GetRoundInfo(ctx context.Context, in *GetRoundInfoRequest, opts ...grpc.CallOption) (*GetRoundInfoResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type poetClient struct {
	cc *grpc.ClientConn
}

func NewPoetClient(cc *grpc.ClientConn) PoetClient {
	return &poetClient{cc}
}

func (c *poetClient) SubmitCommitment(ctx context.Context, in *SubmitCommitmentRequest, opts ...grpc.CallOption) (*SubmitCommitmentResponse, error) {
	out := new(SubmitCommitmentResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/SubmitCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) GetMembershipProof(ctx context.Context, in *GetMembershipProofRequest, opts ...grpc.CallOption) (*GetMembershipProofResponse, error) {
	out := new(GetMembershipProofResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/GetMembershipProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) GetRoundInfo(ctx context.Context, in *GetRoundInfoRequest, opts ...grpc.CallOption) (*GetRoundInfoResponse, error) {
	out := new(GetRoundInfoResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/GetRoundInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poetClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/api.Poet/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoetServer is the server API for Poet service.
type PoetServer interface {
	SubmitCommitment(context.Context, *SubmitCommitmentRequest) (*SubmitCommitmentResponse, error)
	GetMembershipProof(context.Context, *GetMembershipProofRequest) (*GetMembershipProofResponse, error)
	GetRoundInfo(context.Context, *GetRoundInfoRequest) (*GetRoundInfoResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
}

func RegisterPoetServer(s *grpc.Server, srv PoetServer) {
	s.RegisterService(&_Poet_serviceDesc, srv)
}

func _Poet_SubmitCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).SubmitCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/SubmitCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).SubmitCommitment(ctx, req.(*SubmitCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_GetMembershipProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).GetMembershipProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/GetMembershipProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).GetMembershipProof(ctx, req.(*GetMembershipProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_GetRoundInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).GetRoundInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/GetRoundInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).GetRoundInfo(ctx, req.(*GetRoundInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poet_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoetServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Poet/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoetServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Poet",
	HandlerType: (*PoetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCommitment",
			Handler:    _Poet_SubmitCommitment_Handler,
		},
		{
			MethodName: "GetMembershipProof",
			Handler:    _Poet_GetMembershipProof_Handler,
		},
		{
			MethodName: "GetRoundInfo",
			Handler:    _Poet_GetRoundInfo_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Poet_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
