package prover

import (
	"fmt"
	"github.com/spacemeshos/merkle-tree/cache"
	"github.com/spacemeshos/merkle-tree/cache/readwriters"
	"github.com/spacemeshos/smutil/log"
	"os"
	"path/filepath"
)

// ReadWriterMetaFactory generates Merkle LayerFactory functions. The functions it creates generate file read-writers
// starting from the base layer and up to minMemoryLayer-1. From minMemoryLayer and up the functions generate slice
// read-writers.
// The MetaFactory tracks the files it creates and removes them when Cleanup() is called.
type ReadWriterMetaFactory struct {
	minMemoryLayer uint
	datadir        string
	filesCreated   map[string]bool
}

// NewReadWriterMetaFactory returns a new ReadWriterMetaFactory. minMemoryLayer determines
// the threshold in which lower layers caching is done on-disk, while from this layer up -- in-memory
func NewReadWriterMetaFactory(minMemoryLayer uint, datadir string) *ReadWriterMetaFactory {
	return &ReadWriterMetaFactory{
		minMemoryLayer: minMemoryLayer,
		datadir:        datadir,
		filesCreated:   make(map[string]bool),
	}
}

// GetFactory creates a Merkle LayerFactory function.
func (mf *ReadWriterMetaFactory) GetFactory() cache.LayerFactory {
	return func(layerHeight uint) (cache.LayerReadWriter, error) {
		log.Info("#### layerHight %v, minMemory %v", layerHeight, mf.minMemoryLayer)
		if layerHeight < mf.minMemoryLayer {
			fileName, err := mf.makeFileName(layerHeight)
			if err != nil {
				return nil, err
			}

			readWriter, err := readwriters.NewFileReadWriter(fileName)
			if err != nil {
				return nil, err
			}

			mf.filesCreated[fileName] = true
			return readWriter, nil
		}
		return &readwriters.SliceReadWriter{}, nil
	}
}

// Cleanup removes the files that were created by the LayerFactory functions generated by this MetaFactory.
func (mf *ReadWriterMetaFactory) Cleanup() {
	failedRemovals := make(map[string]bool)
	for filename := range mf.filesCreated {
		err := os.Remove(filename)
		if err != nil {
			log.Error("could not remove temp file %v: %v", filename, err)
			failedRemovals[filename] = true
		}
	}
	mf.filesCreated = failedRemovals
}

func (mf *ReadWriterMetaFactory) makeFileName(layer uint) (string, error) {
	return filepath.Join(mf.datadir, fmt.Sprintf("layercache_%d.bin", layer)), nil
}
