package prover

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spacemeshos/merkle-tree/cache"
	"github.com/spacemeshos/merkle-tree/cache/readwriters"
)

// ReadWriterMetaFactory generates Merkle LayerFactory functions. The functions it creates generate file read-writers
// starting from the base layer and up to minMemoryLayer-1. From minMemoryLayer and up the functions generate slice
// read-writers.
// The MetaFactory tracks the files it creates and removes them when Cleanup() is called.
type ReadWriterMetaFactory struct {
	minMemoryLayer    uint
	datadir           string
	filesCreated      map[string]bool
	fileWriterBufSize uint
}

// NewReadWriterMetaFactory returns a new ReadWriterMetaFactory. minMemoryLayer determines
// the threshold in which lower layers caching is done on-disk, while from this layer up -- in-memory.
func NewReadWriterMetaFactory(minMemoryLayer uint, datadir string, fileWriterBufSize uint) *ReadWriterMetaFactory {
	return &ReadWriterMetaFactory{
		minMemoryLayer:    minMemoryLayer,
		datadir:           datadir,
		filesCreated:      make(map[string]bool),
		fileWriterBufSize: fileWriterBufSize,
	}
}

// GetFactory creates a Merkle LayerFactory function.
func (mf *ReadWriterMetaFactory) GetFactory() cache.LayerFactory {
	return func(layerHeight uint) (cache.LayerReadWriter, error) {
		if layerHeight < mf.minMemoryLayer {
			fileName, err := mf.makeFileName(layerHeight)
			if err != nil {
				return nil, err
			}

			readWriter, err := readwriters.NewFileReadWriter(fileName, int(mf.fileWriterBufSize))
			if err != nil {
				return nil, err
			}

			mf.filesCreated[fileName] = true
			return readWriter, nil
		}
		return &readwriters.SliceReadWriter{}, nil
	}
}

// Cleanup removes the files that were created by the LayerFactory functions generated by this MetaFactory.
func (mf *ReadWriterMetaFactory) Cleanup() error {
	var result error
	failedRemovals := make(map[string]bool)
	for filename := range mf.filesCreated {
		err := os.Remove(filename)
		if err != nil {
			result = errors.Join(err, fmt.Errorf("could not remove temp file %v: %w", filename, err))
			failedRemovals[filename] = true
		}
	}
	mf.filesCreated = failedRemovals
	return result
}

func (mf *ReadWriterMetaFactory) makeFileName(layer uint) (string, error) {
	return filepath.Join(mf.datadir, fmt.Sprintf("layercache_%d.bin", layer)), nil
}
