// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rpc/api/v1/api.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Difficulty of the PoW challenge (in terms of leading zero bits in the hash)
	Difficulty uint32 `protobuf:"varint,1,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	// The challenge to be used for the PoW
	Challenge     []byte `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowParams) Reset() {
	*x = PowParams{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowParams) ProtoMessage() {}

func (x *PowParams) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowParams.ProtoReflect.Descriptor instead.
func (*PowParams) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *PowParams) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *PowParams) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type PowParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowParamsRequest) Reset() {
	*x = PowParamsRequest{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowParamsRequest) ProtoMessage() {}

func (x *PowParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowParamsRequest.ProtoReflect.Descriptor instead.
func (*PowParamsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{1}
}

type PowParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PowParams     *PowParams             `protobuf:"bytes,1,opt,name=pow_params,json=powParams,proto3" json:"pow_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowParamsResponse) Reset() {
	*x = PowParamsResponse{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowParamsResponse) ProtoMessage() {}

func (x *PowParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowParamsResponse.ProtoReflect.Descriptor instead.
func (*PowParamsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *PowParamsResponse) GetPowParams() *PowParams {
	if x != nil {
		return x.PowParams
	}
	return nil
}

type SubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Proof of Work nonce
	// deprecated - use certificate instead
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Proof of Work parameters that were used to generate the nonce
	// deprecated - use certificate instead
	PowParams *PowParams `protobuf:"bytes,2,opt,name=pow_params,json=powParams,proto3" json:"pow_params,omitempty"`
	// Prefix to be added to challenge for signature verification
	Prefix []byte `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// The PoET challenge to be registered for the open round
	Challenge []byte `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// The user's public key (node ID)
	Pubkey []byte `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The user's signature over the challenge
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// The time by which the proof is needed.
	// If the currently open round will end after this time
	// and the  proof cannot be generated by this time, the request will be rejected.
	Deadline              *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Certificate           *SubmitRequest_Certificate `protobuf:"bytes,8,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CertificatePubkeyHint []byte                     `protobuf:"bytes,9,opt,name=certificate_pubkey_hint,json=certificatePubkeyHint,proto3" json:"certificate_pubkey_hint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SubmitRequest) GetPowParams() *PowParams {
	if x != nil {
		return x.PowParams
	}
	return nil
}

func (x *SubmitRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *SubmitRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *SubmitRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SubmitRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *SubmitRequest) GetCertificate() *SubmitRequest_Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *SubmitRequest) GetCertificatePubkeyHint() []byte {
	if x != nil {
		return x.CertificatePubkeyHint
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	RoundEnd      *durationpb.Duration   `protobuf:"bytes,3,opt,name=round_end,json=roundEnd,proto3" json:"round_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SubmitResponse) GetRoundEnd() *durationpb.Duration {
	if x != nil {
		return x.RoundEnd
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{5}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServicePubkey []byte                 `protobuf:"bytes,3,opt,name=service_pubkey,json=servicePubkey,proto3" json:"service_pubkey,omitempty"`
	PhaseShift    *durationpb.Duration   `protobuf:"bytes,4,opt,name=phase_shift,json=phaseShift,proto3" json:"phase_shift,omitempty"`
	CycleGap      *durationpb.Duration   `protobuf:"bytes,5,opt,name=cycle_gap,json=cycleGap,proto3" json:"cycle_gap,omitempty"`
	Certifier     *InfoResponse_Cerifier `protobuf:"bytes,6,opt,name=certifier,proto3" json:"certifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *InfoResponse) GetServicePubkey() []byte {
	if x != nil {
		return x.ServicePubkey
	}
	return nil
}

func (x *InfoResponse) GetPhaseShift() *durationpb.Duration {
	if x != nil {
		return x.PhaseShift
	}
	return nil
}

func (x *InfoResponse) GetCycleGap() *durationpb.Duration {
	if x != nil {
		return x.CycleGap
	}
	return nil
}

func (x *InfoResponse) GetCertifier() *InfoResponse_Cerifier {
	if x != nil {
		return x.Certifier
	}
	return nil
}

type MembershipProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Proof         [][]byte               `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipProof) Reset() {
	*x = MembershipProof{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipProof) ProtoMessage() {}

func (x *MembershipProof) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipProof.ProtoReflect.Descriptor instead.
func (*MembershipProof) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *MembershipProof) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MembershipProof) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *MembershipProof) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type MerkleProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          []byte                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	ProvenLeaves  [][]byte               `protobuf:"bytes,2,rep,name=proven_leaves,json=provenLeaves,proto3" json:"proven_leaves,omitempty"`
	ProofNodes    [][]byte               `protobuf:"bytes,3,rep,name=proof_nodes,json=proofNodes,proto3" json:"proof_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProof) Reset() {
	*x = MerkleProof{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProof) ProtoMessage() {}

func (x *MerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProof.ProtoReflect.Descriptor instead.
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *MerkleProof) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *MerkleProof) GetProvenLeaves() [][]byte {
	if x != nil {
		return x.ProvenLeaves
	}
	return nil
}

func (x *MerkleProof) GetProofNodes() [][]byte {
	if x != nil {
		return x.ProofNodes
	}
	return nil
}

type PoetProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *MerkleProof           `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Members       [][]byte               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Leaves        uint64                 `protobuf:"varint,3,opt,name=leaves,proto3" json:"leaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoetProof) Reset() {
	*x = PoetProof{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoetProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoetProof) ProtoMessage() {}

func (x *PoetProof) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoetProof.ProtoReflect.Descriptor instead.
func (*PoetProof) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *PoetProof) GetProof() *MerkleProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *PoetProof) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *PoetProof) GetLeaves() uint64 {
	if x != nil {
		return x.Leaves
	}
	return 0
}

type ProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofRequest) Reset() {
	*x = ProofRequest{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofRequest) ProtoMessage() {}

func (x *ProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofRequest.ProtoReflect.Descriptor instead.
func (*ProofRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *ProofRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type ProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *PoetProof             `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofResponse) Reset() {
	*x = ProofResponse{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofResponse) ProtoMessage() {}

func (x *ProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofResponse.ProtoReflect.Descriptor instead.
func (*ProofResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *ProofResponse) GetProof() *PoetProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ProofResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SubmitRequest_Certificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The certifier's signature over `data`
	// confirming that the pubkey is verified.
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest_Certificate) Reset() {
	*x = SubmitRequest_Certificate{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest_Certificate) ProtoMessage() {}

func (x *SubmitRequest_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest_Certificate.ProtoReflect.Descriptor instead.
func (*SubmitRequest_Certificate) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SubmitRequest_Certificate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubmitRequest_Certificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type InfoResponse_Cerifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse_Cerifier) Reset() {
	*x = InfoResponse_Cerifier{}
	mi := &file_rpc_api_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse_Cerifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse_Cerifier) ProtoMessage() {}

func (x *InfoResponse_Cerifier) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse_Cerifier.ProtoReflect.Descriptor instead.
func (*InfoResponse_Cerifier) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *InfoResponse_Cerifier) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InfoResponse_Cerifier) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

var File_rpc_api_v1_api_proto protoreflect.FileDescriptor

const file_rpc_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/api/v1/api.proto\x12\n" +
	"rpc.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\tPowParams\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\rR\n" +
	"difficulty\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\"\x12\n" +
	"\x10PowParamsRequest\"I\n" +
	"\x11PowParamsResponse\x124\n" +
	"\n" +
	"pow_params\x18\x01 \x01(\v2\x15.rpc.api.v1.PowParamsR\tpowParams\"\xc1\x03\n" +
	"\rSubmitRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x124\n" +
	"\n" +
	"pow_params\x18\x02 \x01(\v2\x15.rpc.api.v1.PowParamsR\tpowParams\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\fR\x06prefix\x12\x1c\n" +
	"\tchallenge\x18\x04 \x01(\fR\tchallenge\x12\x16\n" +
	"\x06pubkey\x18\x05 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12G\n" +
	"\vcertificate\x18\b \x01(\v2%.rpc.api.v1.SubmitRequest.CertificateR\vcertificate\x126\n" +
	"\x17certificate_pubkey_hint\x18\t \x01(\fR\x15certificatePubkeyHint\x1a?\n" +
	"\vCertificate\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"c\n" +
	"\x0eSubmitResponse\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x126\n" +
	"\tround_end\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\broundEnd\"\r\n" +
	"\vInfoRequest\"\xac\x02\n" +
	"\fInfoResponse\x12%\n" +
	"\x0eservice_pubkey\x18\x03 \x01(\fR\rservicePubkey\x12:\n" +
	"\vphase_shift\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"phaseShift\x126\n" +
	"\tcycle_gap\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bcycleGap\x12?\n" +
	"\tcertifier\x18\x06 \x01(\v2!.rpc.api.v1.InfoResponse.CerifierR\tcertifier\x1a4\n" +
	"\bCerifier\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkeyJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"Q\n" +
	"\x0fMembershipProof\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x14\n" +
	"\x05proof\x18\x03 \x03(\fR\x05proof\"g\n" +
	"\vMerkleProof\x12\x12\n" +
	"\x04root\x18\x01 \x01(\fR\x04root\x12#\n" +
	"\rproven_leaves\x18\x02 \x03(\fR\fprovenLeaves\x12\x1f\n" +
	"\vproof_nodes\x18\x03 \x03(\fR\n" +
	"proofNodes\"l\n" +
	"\tPoetProof\x12-\n" +
	"\x05proof\x18\x01 \x01(\v2\x17.rpc.api.v1.MerkleProofR\x05proof\x12\x18\n" +
	"\amembers\x18\x02 \x03(\fR\amembers\x12\x16\n" +
	"\x06leaves\x18\x03 \x01(\x04R\x06leaves\")\n" +
	"\fProofRequest\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\"T\n" +
	"\rProofResponse\x12+\n" +
	"\x05proof\x18\x01 \x01(\v2\x15.rpc.api.v1.PoetProofR\x05proof\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey2\xf1\x02\n" +
	"\vPoetService\x12`\n" +
	"\tPowParams\x12\x1c.rpc.api.v1.PowParamsRequest\x1a\x1d.rpc.api.v1.PowParamsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/pow_params\x12V\n" +
	"\x06Submit\x12\x19.rpc.api.v1.SubmitRequest\x1a\x1a.rpc.api.v1.SubmitResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/submit\x12K\n" +
	"\x04Info\x12\x17.rpc.api.v1.InfoRequest\x1a\x18.rpc.api.v1.InfoResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/info\x12[\n" +
	"\x05Proof\x12\x18.rpc.api.v1.ProofRequest\x1a\x19.rpc.api.v1.ProofResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/proofs/{round_id}B\xa3\x01\n" +
	"\x0ecom.rpc.api.v1B\bApiProtoP\x01Z=github.com/spacemeshos/poet/release/proto/go/rpc/api/v1;apiv1\xa2\x02\x03RAX\xaa\x02\n" +
	"Rpc.Api.V1\xca\x02\n" +
	"Rpc\\Api\\V1\xe2\x02\x16Rpc\\Api\\V1\\GPBMetadata\xea\x02\fRpc::Api::V1b\x06proto3"

var (
	file_rpc_api_v1_api_proto_rawDescOnce sync.Once
	file_rpc_api_v1_api_proto_rawDescData []byte
)

func file_rpc_api_v1_api_proto_rawDescGZIP() []byte {
	file_rpc_api_v1_api_proto_rawDescOnce.Do(func() {
		file_rpc_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_api_v1_api_proto_rawDesc), len(file_rpc_api_v1_api_proto_rawDesc)))
	})
	return file_rpc_api_v1_api_proto_rawDescData
}

var file_rpc_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_api_v1_api_proto_goTypes = []any{
	(*PowParams)(nil),                 // 0: rpc.api.v1.PowParams
	(*PowParamsRequest)(nil),          // 1: rpc.api.v1.PowParamsRequest
	(*PowParamsResponse)(nil),         // 2: rpc.api.v1.PowParamsResponse
	(*SubmitRequest)(nil),             // 3: rpc.api.v1.SubmitRequest
	(*SubmitResponse)(nil),            // 4: rpc.api.v1.SubmitResponse
	(*InfoRequest)(nil),               // 5: rpc.api.v1.InfoRequest
	(*InfoResponse)(nil),              // 6: rpc.api.v1.InfoResponse
	(*MembershipProof)(nil),           // 7: rpc.api.v1.MembershipProof
	(*MerkleProof)(nil),               // 8: rpc.api.v1.MerkleProof
	(*PoetProof)(nil),                 // 9: rpc.api.v1.PoetProof
	(*ProofRequest)(nil),              // 10: rpc.api.v1.ProofRequest
	(*ProofResponse)(nil),             // 11: rpc.api.v1.ProofResponse
	(*SubmitRequest_Certificate)(nil), // 12: rpc.api.v1.SubmitRequest.Certificate
	(*InfoResponse_Cerifier)(nil),     // 13: rpc.api.v1.InfoResponse.Cerifier
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 15: google.protobuf.Duration
}
var file_rpc_api_v1_api_proto_depIdxs = []int32{
	0,  // 0: rpc.api.v1.PowParamsResponse.pow_params:type_name -> rpc.api.v1.PowParams
	0,  // 1: rpc.api.v1.SubmitRequest.pow_params:type_name -> rpc.api.v1.PowParams
	14, // 2: rpc.api.v1.SubmitRequest.deadline:type_name -> google.protobuf.Timestamp
	12, // 3: rpc.api.v1.SubmitRequest.certificate:type_name -> rpc.api.v1.SubmitRequest.Certificate
	15, // 4: rpc.api.v1.SubmitResponse.round_end:type_name -> google.protobuf.Duration
	15, // 5: rpc.api.v1.InfoResponse.phase_shift:type_name -> google.protobuf.Duration
	15, // 6: rpc.api.v1.InfoResponse.cycle_gap:type_name -> google.protobuf.Duration
	13, // 7: rpc.api.v1.InfoResponse.certifier:type_name -> rpc.api.v1.InfoResponse.Cerifier
	8,  // 8: rpc.api.v1.PoetProof.proof:type_name -> rpc.api.v1.MerkleProof
	9,  // 9: rpc.api.v1.ProofResponse.proof:type_name -> rpc.api.v1.PoetProof
	1,  // 10: rpc.api.v1.PoetService.PowParams:input_type -> rpc.api.v1.PowParamsRequest
	3,  // 11: rpc.api.v1.PoetService.Submit:input_type -> rpc.api.v1.SubmitRequest
	5,  // 12: rpc.api.v1.PoetService.Info:input_type -> rpc.api.v1.InfoRequest
	10, // 13: rpc.api.v1.PoetService.Proof:input_type -> rpc.api.v1.ProofRequest
	2,  // 14: rpc.api.v1.PoetService.PowParams:output_type -> rpc.api.v1.PowParamsResponse
	4,  // 15: rpc.api.v1.PoetService.Submit:output_type -> rpc.api.v1.SubmitResponse
	6,  // 16: rpc.api.v1.PoetService.Info:output_type -> rpc.api.v1.InfoResponse
	11, // 17: rpc.api.v1.PoetService.Proof:output_type -> rpc.api.v1.ProofResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_api_v1_api_proto_init() }
func file_rpc_api_v1_api_proto_init() {
	if File_rpc_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_api_v1_api_proto_rawDesc), len(file_rpc_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_api_v1_api_proto_goTypes,
		DependencyIndexes: file_rpc_api_v1_api_proto_depIdxs,
		MessageInfos:      file_rpc_api_v1_api_proto_msgTypes,
	}.Build()
	File_rpc_api_v1_api_proto = out.File
	file_rpc_api_v1_api_proto_goTypes = nil
	file_rpc_api_v1_api_proto_depIdxs = nil
}
