// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rpc/api/v1/internal_api.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloadTrustedKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadTrustedKeysRequest) Reset() {
	*x = ReloadTrustedKeysRequest{}
	mi := &file_rpc_api_v1_internal_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadTrustedKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadTrustedKeysRequest) ProtoMessage() {}

func (x *ReloadTrustedKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_internal_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadTrustedKeysRequest.ProtoReflect.Descriptor instead.
func (*ReloadTrustedKeysRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_internal_api_proto_rawDescGZIP(), []int{0}
}

type ReloadTrustedKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadTrustedKeysResponse) Reset() {
	*x = ReloadTrustedKeysResponse{}
	mi := &file_rpc_api_v1_internal_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadTrustedKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadTrustedKeysResponse) ProtoMessage() {}

func (x *ReloadTrustedKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_v1_internal_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadTrustedKeysResponse.ProtoReflect.Descriptor instead.
func (*ReloadTrustedKeysResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_v1_internal_api_proto_rawDescGZIP(), []int{1}
}

var File_rpc_api_v1_internal_api_proto protoreflect.FileDescriptor

const file_rpc_api_v1_internal_api_proto_rawDesc = "" +
	"\n" +
	"\x1drpc/api/v1/internal_api.proto\x12\n" +
	"rpc.api.v1\x1a\x1cgoogle/api/annotations.proto\"\x1a\n" +
	"\x18ReloadTrustedKeysRequest\"\x1b\n" +
	"\x19ReloadTrustedKeysResponse2\x9a\x01\n" +
	"\x14ConfigurationService\x12\x81\x01\n" +
	"\x11ReloadTrustedKeys\x12$.rpc.api.v1.ReloadTrustedKeysRequest\x1a%.rpc.api.v1.ReloadTrustedKeysResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/reload_trusted_keysB\xab\x01\n" +
	"\x0ecom.rpc.api.v1B\x10InternalApiProtoP\x01Z=github.com/spacemeshos/poet/release/proto/go/rpc/api/v1;apiv1\xa2\x02\x03RAX\xaa\x02\n" +
	"Rpc.Api.V1\xca\x02\n" +
	"Rpc\\Api\\V1\xe2\x02\x16Rpc\\Api\\V1\\GPBMetadata\xea\x02\fRpc::Api::V1b\x06proto3"

var (
	file_rpc_api_v1_internal_api_proto_rawDescOnce sync.Once
	file_rpc_api_v1_internal_api_proto_rawDescData []byte
)

func file_rpc_api_v1_internal_api_proto_rawDescGZIP() []byte {
	file_rpc_api_v1_internal_api_proto_rawDescOnce.Do(func() {
		file_rpc_api_v1_internal_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_api_v1_internal_api_proto_rawDesc), len(file_rpc_api_v1_internal_api_proto_rawDesc)))
	})
	return file_rpc_api_v1_internal_api_proto_rawDescData
}

var file_rpc_api_v1_internal_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_api_v1_internal_api_proto_goTypes = []any{
	(*ReloadTrustedKeysRequest)(nil),  // 0: rpc.api.v1.ReloadTrustedKeysRequest
	(*ReloadTrustedKeysResponse)(nil), // 1: rpc.api.v1.ReloadTrustedKeysResponse
}
var file_rpc_api_v1_internal_api_proto_depIdxs = []int32{
	0, // 0: rpc.api.v1.ConfigurationService.ReloadTrustedKeys:input_type -> rpc.api.v1.ReloadTrustedKeysRequest
	1, // 1: rpc.api.v1.ConfigurationService.ReloadTrustedKeys:output_type -> rpc.api.v1.ReloadTrustedKeysResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_api_v1_internal_api_proto_init() }
func file_rpc_api_v1_internal_api_proto_init() {
	if File_rpc_api_v1_internal_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_api_v1_internal_api_proto_rawDesc), len(file_rpc_api_v1_internal_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_api_v1_internal_api_proto_goTypes,
		DependencyIndexes: file_rpc_api_v1_internal_api_proto_depIdxs,
		MessageInfos:      file_rpc_api_v1_internal_api_proto_msgTypes,
	}.Build()
	File_rpc_api_v1_internal_api_proto = out.File
	file_rpc_api_v1_internal_api_proto_goTypes = nil
	file_rpc_api_v1_internal_api_proto_depIdxs = nil
}
