// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package shared

import (
	"github.com/spacemeshos/go-scale"
)

func (t *MerkleProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	if n, err := scale.EncodeByteSlice(enc, t.Root); err != nil {
		return total, err
	} else {
		total += n
	}
	if n, err := scale.EncodeSliceOfByteSlice(enc, t.ProvenLeaves); err != nil {
		return total, err
	} else {
		total += n
	}
	if n, err := scale.EncodeSliceOfByteSlice(enc, t.ProofNodes); err != nil {
		return total, err
	} else {
		total += n
	}
	return total, nil
}

func (t *MerkleProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	if field, n, err := scale.DecodeByteSlice(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Root = field
	}
	if field, n, err := scale.DecodeSliceOfByteSlice(dec); err != nil {
		return total, err
	} else {
		total += n
		t.ProvenLeaves = field
	}
	if field, n, err := scale.DecodeSliceOfByteSlice(dec); err != nil {
		return total, err
	} else {
		total += n
		t.ProofNodes = field
	}
	return total, nil
}
