name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  verify_protos:
    runs-on: ubuntu-latest
    steps:
      - name: Lint protos
        run: make lint-protos
        continue-on-error: true
      - name: Verify if files built from .proto are up to date.
        run: make check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: test
        run: go test -v ./...
